### ISSUE TITLE
modbus connection to the PKOM4

### ISSUE THREAD

**Issue by vitkolar** [jtasoftware/homebridge-pkom4-plugin#1]
**Describe Your Problem:**

Hello, I got a question not about the plugin but it is related to PKOM4, but please read on.
as the first step, I wanted to connect to PKOM with USR-TCP232-410S. I connected to the M1 connector on the main board.
I used speed as specified in the settings I found in your repo.
Setup instrument using serial port name & address (ignored for demo mode)
PKOM uses Modbus 8E1 setup at 19200 bauds over slave address 41
8E1 (8 data bits, Even Parity, 1 stop bit)

instrument = minimalmodbus.Instrument(serialPort, 41, minimalmodbus.MODE_RTU)
instrument.serial.baudrate = 19200

for some reason when I scan Modbus i don't get any response:
![image](https://user-images.githubusercontent.com/64085695/233828949-77aebe24-dedb-4e7a-b5ca-1391a6643482.png)

Please would you have an idea what could be the reason not receiving anything? 
Does PKOM external control need to be set beforehand? Besides the M1 connector, there is an LED and a jumper. Led does not blink, while the same status LEDs besides other Modbus connectors blink.

**Screenshots:**

![image](https://user-images.githubusercontent.com/64085695/233828614-217e8d4e-67e4-433c-b4c4-64e981a70d58.png)
![image](https://user-images.githubusercontent.com/64085695/233828696-e7b243b8-a404-48ab-a4f6-7a368e2aa33b.png)

**Environment:**

* **Plugin Version**: NA
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by vitkolar** [comment]
I got the solution. Work Mode: TCP server, Modbus TCP :)
![image](https://user-images.githubusercontent.com/64085695/234685086-9cff6741-826a-4d4f-939c-f9f46bd526ce.png)

**Comment by jtasoftware** [comment]
Thanks Vikilar for sharing your findings.
